### ISSUE TITLE
CloneNetworkTask cloneNetwork method is private

### ISSUE THREAD

**Issue by spqrPh** [cytoscape/cytoscape-impl#31]
Hi,

The method I'm referring to is: private CyNetwork cloneNetwork(final CyNetwork origNet)
I'm wondering why this method is private. Right now the only way of cloning/copying a network seems to be the CloneNetworkTaskFactory which generates a view in addition to cloning.
I'm working on a clustering app where I want to preserve a copy of the original network for further reference associated with a solution. 
Is there a certain reason behind not exposing this method, should I use a different way of copying/cloning?

**Comment by AlexanderPico** [comment]
Filed as a feature request: http://code.cytoscape.org/redmine/issues/3938.  Thanks for reporting!
